### ISSUE TITLE
Feedback section 7.6 and 8

### ISSUE THREAD

**Issue by snkas** [mihaibudiu/sigmod-rh#13]
My feedback focuses on section 7.6 and 8.

**Text section 7.6:**
- Introduction to Feldera in the last paragraph needs some more context, as in, it could have already been introduced at the start of section 7.3
- The reference to Fig. 6 should mention that it is the local form factor architecture, with maybe additionally a mention that there also is another form factor, the cloud form factor, which distributes the pipeline manager across several communicating services and uses Kubernetes to run the pipelines.

**Text section 8:**
- Q: Would it make a difference if the DBSP process would be pinned to 16 cores?
- Q: Which settings were explored for Flink and did not provide different/better performance? E.g., the ratio of cores/task manager?
- Wording: sentence "We did not include the control plane in either case (in Feldera, the pipeline manager; in Flink, the job manager)." could be clearer by adding something along the lines of: "In the total memory sum we did not..."
- Typo: 8.2 last sentence: "storage reduces the storage significantly" -> likely memory consumption is intended for the second "storage"

**Figure 9:**
- The 90 degree labels under each bar can be left out as there is already a legend
- The headers Throughput and Peak Memory Usage, can be part of the y-axis label: "Avg. throughput (events/s)", "Peak memory usage (GiB)"
- The query numbers at the top should be larger and prefixed with "Q" (potentially, moved to the bottom)
- The legend on the right can be at the top horizontal, saving x-axis space
- Colors could be more distinct (especially orange vs. red)
- In general, larger font sizes for the text

**Comment by blp** [comment]
I was able to improve the figure in most of those ways: https://github.com/mihaibudiu/sigmod-rh/pull/15. I don't know how to add "Q" to the query numbers in the labels.
